# Generated by Django 3.1.1 on 2020-10-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('parentId', models.IntegerField(blank=True, null=True, verbose_name='родительская категория')),
                ('url', models.CharField(blank=True, max_length=128, verbose_name='ссылка')),
                ('in_Menu', models.BooleanField(default=True, verbose_name='в меню')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('banner', models.ImageField(blank=True, upload_to='product_image', verbose_name='верхний баннер')),
                ('logo', models.ImageField(blank=True, upload_to='product_image', verbose_name='логотип')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Small_texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, null=True, verbose_name='буллет')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm_texts', to='mainapp.product', verbose_name='Текстовый буллет')),
            ],
            options={
                'verbose_name': 'Буллет',
                'verbose_name_plural': 'Буллеты',
            },
        ),
        migrations.CreateModel(
            name='SizeAndPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена размера')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='mainapp.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер и цена',
                'verbose_name_plural': 'Размеры и цены',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_image', verbose_name='рисунок галереи')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.product')),
            ],
            options={
                'verbose_name': 'Рисунок',
                'verbose_name_plural': 'Рисунки для галереи',
            },
        ),
    ]
