# Generated by Django 3.1.1 on 2020-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parentId',
            field=models.IntegerField(default=0, verbose_name='родительская категория'),
            preserve_default=False,
        ),
    ]
